apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-fqtb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-nodevfile-nodocker-rhtap-three-component-scenarios-fqtb
    app.kubernetes.io/part-of: mc-three-scenarios
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-fqtb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-fqtb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-fqtb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-lfaq-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-fqtb@sha256:7bc554e2a94905d23cba0d2cde0262444e6dd7815de75cd63fd86993446ba124
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
