apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-bz7d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-rhtap-three-component-scenarios-bz7d
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-go-rhtap-three-component-scenarios-bz7d
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-bz7d
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-bz7d
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-lfaq-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-bz7d@sha256:a453c2f5431d85f970fe83b2e851c39560a0b06f5a9505048d60dae0fef3bfd8
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
